services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # backend
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway_container
    ports:
      - "5000:5000"
    volumes:
    - ./api-gateway:/app
    - /app/node_modules
    env_file:
      - ./api-gateway/.env
    environment:
      - AUTH_SERVICE=http://backend-auth:5001
    depends_on:
      - backend-auth
  backend-auth:
    build: ./backend-auth
    container_name: backend_auth_container
    ports:
      - "5001:5001"
    volumes:
    - ./backend-auth:/app
    - /app/node_modules
    env_file:
      - ./backend-auth/.env
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  # frontend
  auth-frontend:
    build: ./frontend-auth
    container_name: frontend_auth_container
    ports:
      - "5173:5173"
    volumes:
    - ./frontend-auth:/app
    - /app/node_modules
    depends_on:
    - api-gateway

volumes:
  mongo-data: